[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXTAUTH_URL = "https://odontoflash.netlify.app"
  NEXTAUTH_SECRET = "your-secret-key-here"
  DATABASE_URL = "postgresql://username:password@localhost:5432/odontoflash"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
